name: Test

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install nightly --profile minimal
      - run: rustup default nightly
      - run: cargo build # Need to build before testing saft-test crate :/
      - run: cargo test --all

  format:
    name: Format

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install nightly --profile minimal
      - run: rustup default nightly
      - run: rustup component add rustfmt
      - run: cargo fmt --all --check

  lint:
    name: Lint

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -DWarnings

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install nightly --profile minimal
      - run: rustup default nightly
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features
